snakes = {
    "jararaca_da_seca": {
        "name": "Jararaca-da-seca",
        "scientific": "Bothrops erythromelas",
        "venomous": True,
        "venom_type": "Hemotoxico",
        "protected": False,
        "protection_status": "Nao ameacada",
        "description": "Endemica do Nordeste brasileiro, e a principal causa de acidentes ofidicos na Caatinga. Coloracao parda com manchas escuras.",
        "first_aid": "Imobilize o membro afetado, nao faca torniquete e busque atendimento medico imediatamente.",
    },
    "cascavel": {
        "name": "Cascavel",
        "scientific": "Crotalus durissus",
        "venomous": True,
        "venom_type": "Neurotoxico",
        "protected": False,
        "protection_status": "Nao ameacada",
        "description": "Reconhecivel pelo guizo na cauda. Presente em areas abertas da Caatinga. Veneno de acao neurologica, extremamente perigoso.",
        "first_aid": "Nao movimente a vitima, mantenha-a deitada e busque hospital com antipeconhento urgente.",
    },
    "coral_verdadeira": {
        "name": "Coral-verdadeira",
        "scientific": "Micrurus ibiboboca",
        "venomous": True,
        "venom_type": "Neurotoxico",
        "protected": True,
        "protection_status": "Monitorada pelo ICMBio/RAN",
        "description": "A mais venenosa do Brasil. Aneis coloridos em vermelho, preto e branco. Endemica do Nordeste.",
        "first_aid": "Busque atendimento medico imediatamente. Nao tente sugar o veneno ou fazer cortes.",
    },
    "coral_falsa": {
        "name": "Coral-falsa",
        "scientific": "Oxyrhopus trigeminus",
        "venomous": False,
        "venom_type": None,
        "protected": False,
        "protection_status": "Nao ameacada",
        "description": "Imita visualmente a coral-verdadeira, sendo frequentemente morta por engano. Nao representa perigo para humanos.",
        "first_aid": None,
    },
    "cobra_cipo": {
        "name": "Cobra-cipo",
        "scientific": "Philodryas nattereri",
        "venomous": False,
        "venom_type": None,
        "protected": False,
        "protection_status": "Nao ameacada",
        "description": "A especie mais comum da Caatinga. Agil e arboricola, nao representa risco significativo para humanos.",
        "first_aid": None,
    },
    "jiboia": {
        "name": "Jiboia",
        "scientific": "Boa constrictor",
        "venomous": False,
        "venom_type": None,
        "protected": True,
        "protection_status": "Protegida em varios estados",
        "description": "Mata por constricao, nao possui veneno. Muito cacada no interior. Importante para o equilibrio do ecossistema.",
        "first_aid": None,
    },
}
