export const snakes = [
  {
    id: 1,
    name: 'Jararaca-da-seca',
    scientific: 'Bothrops erythromelas',
    venomous: true,
    venom_type: 'Hemotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Endêmica do Nordeste brasileiro, é a principal causa de acidentes ofídicos na Caatinga. Coloração parda com manchas escuras em forma de triângulo.',
    first_aid: 'Imobilize o membro afetado, não faça torniquete e busque atendimento médico imediatamente.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bothrops_erythromelas.jpg/320px-Bothrops_erythromelas.jpg',
    characteristics: ['Coloração parda com manchas escuras', 'Cabeça triangular bem definida', 'Corpo robusto e curto', 'Escamas quilhadas'],
  },
  {
    id: 2,
    name: 'Cascavel',
    scientific: 'Crotalus durissus',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Reconhecível pelo guizo na cauda. Presente em áreas abertas da Caatinga. Veneno de ação neurológica, extremamente perigoso.',
    first_aid: 'Não movimente a vítima, mantenha-a deitada e busque hospital com antipeçonhento urgente.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Crotalus_durissus_terrificus.jpg/320px-Crotalus_durissus_terrificus.jpg',
    characteristics: ['Guizo característico na cauda', 'Coloração amarelada com losangos', 'Cabeça larga e triangular', 'Fosseta loreal visível'],
  },
  {
    id: 3,
    name: 'Coral-verdadeira',
    scientific: 'Micrurus ibiboboca',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: true,
    protection_status: 'Monitorada pelo ICMBio/RAN',
    description: 'A mais venenosa do Brasil. Anéis coloridos em vermelho, preto e branco. Endêmica do Nordeste.',
    first_aid: 'Busque atendimento médico imediatamente. Não tente sugar o veneno ou fazer cortes.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Micrurus_ibiboboca.jpg/320px-Micrurus_ibiboboca.jpg',
    characteristics: ['Anéis vermelhos, pretos e brancos', 'Corpo cilíndrico e esbelto', 'Cabeça pequena e arredondada', 'Focinho vermelho'],
  },
  {
    id: 4,
    name: 'Coral-falsa',
    scientific: 'Oxyrhopus trigeminus',
    venomous: false,
    venom_type: null,
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Imita visualmente a coral-verdadeira, sendo frequentemente morta por engano. Não representa perigo para humanos.',
    first_aid: null,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Oxyrhopus_trigeminus.jpg/320px-Oxyrhopus_trigeminus.jpg',
    characteristics: ['Anéis vermelhos e pretos sem branco', 'Corpo mais robusto que a coral-verdadeira', 'Cabeça levemente distinta do corpo', 'Olhos maiores'],
  },
  {
    id: 5,
    name: 'Cobra-cipó',
    scientific: 'Philodryas nattereri',
    venomous: false,
    venom_type: null,
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'A espécie mais comum da Caatinga. Ágil e arborícola, não representa risco significativo para humanos.',
    first_aid: null,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Philodryas_nattereri.jpg/320px-Philodryas_nattereri.jpg',
    characteristics: ['Coloração verde ou parda', 'Corpo esbelto e alongado', 'Olhos grandes', 'Muito ágil'],
  },
  {
    id: 6,
    name: 'Jiboia',
    scientific: 'Boa constrictor',
    venomous: false,
    venom_type: null,
    protected: true,
    protection_status: 'Protegida em vários estados',
    description: 'Mata por constrição, não possui veneno. Muito caçada no interior. Importante para o equilíbrio do ecossistema.',
    first_aid: null,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Boa_constrictor_1.jpg/320px-Boa_constrictor_1.jpg',
    characteristics: ['Corpo grande e robusto', 'Padrão de manchas em selas', 'Cabeça alongada e distinta', 'Pode atingir mais de 3 metros'],
  },
];
