export const snakes = [
  {
    id: 1,
    name: 'Jararaca-da-seca',
    scientific: 'Bothrops erythromelas',
    venomous: true,
    venom_type: 'Hemotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Endêmica do Nordeste brasileiro, é a principal causa de acidentes ofídicos na Caatinga. Coloração parda com manchas escuras.',
    first_aid: 'Imobilize o membro afetado, não faça torniquete e busque atendimento médico imediatamente.',
  },
  {
    id: 2,
    name: 'Cascavel',
    scientific: 'Crotalus durissus',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Reconhecível pelo guizo na cauda. Presente em áreas abertas da Caatinga. Veneno de ação neurológica, extremamente perigoso.',
    first_aid: 'Não movimente a vítima, mantenha-a deitada e busque hospital com antipeçonhento urgente.',
  },
  {
    id: 3,
    name: 'Coral-verdadeira',
    scientific: 'Micrurus ibiboboca',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: true,
    protection_status: 'Monitorada pelo ICMBio/RAN',
    description: 'A mais venenosa do Brasil. Anéis coloridos em vermelho, preto e branco. Endêmica do Nordeste.',
    first_aid: 'Busque atendimento médico imediatamente. Não tente sugar o veneno ou fazer cortes.',
  },
  {
    id: 4,
    name: 'Coral-falsa',
    scientific: 'Oxyrhopus trigeminus',
    venomous: false,
    venom_type: null,
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Imita visualmente a coral-verdadeira, sendo frequentemente morta por engano. Não representa perigo para humanos.',
    first_aid: null,
  },
  {
    id: 5,
    name: 'Cobra-cipó',
    scientific: 'Philodryas nattereri',
    venomous: false,
    venom_type: null,
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'A espécie mais comum da Caatinga. Ágil e arborícola, não representa risco significativo para humanos.',
    first_aid: null,
  },
  {
    id: 6,
    name: 'Jiboia',
    scientific: 'Boa constrictor',
    venomous: false,
    venom_type: null,
    protected: true,
    protection_status: 'Protegida em vários estados',
    description: 'Mata por constrição, não possui veneno. Muito caçada no interior. Importante para o equilíbrio do ecossistema.',
    first_aid: null,
  },
];
