export const snakes = [
  {
    id: 1,
    name: 'Jararaca-da-seca',
    scientific: 'Bothrops erythromelas',
    venomous: true,
    venom_type: 'Hemotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Endêmica do Nordeste brasileiro, é a principal causa de acidentes ofídicos na Caatinga. Coloração parda com manchas escuras em forma de triângulo.',
    first_aid: 'Imobilize o membro afetado, não faça torniquete e busque atendimento médico imediatamente.',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/728418622/large.jpg',
    characteristics: ['Coloração parda com manchas escuras', 'Cabeça triangular bem definida', 'Corpo robusto e curto', 'Escamas quilhadas'],
  },
  {
    id: 2,
    name: 'Cascavel',
    scientific: 'Crotalus durissus',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Reconhecível pelo guizo na cauda. Presente em áreas abertas da Caatinga. Veneno de ação neurológica, extremamente perigoso.',
    first_aid: 'Não movimente a vítima, mantenha-a deitada e busque hospital com antipeçonhento urgente.',
    image: 'https://static.inaturalist.org/photos/726648354/large.jpg',
    characteristics: ['Guizo característico na cauda', 'Coloração amarelada com losangos', 'Cabeça larga e triangular', 'Fosseta loreal visível'],
  },
  {
    id: 3,
    name: 'Coral-verdadeira',
    scientific: 'Micrurus ibiboboca',
    venomous: true,
    venom_type: 'Neurotóxico',
    protected: true,
    protection_status: 'Monitorada pelo ICMBio/RAN',
    description: 'A mais venenosa do Brasil. Anéis coloridos em vermelho, preto e branco. Endêmica do Nordeste.',
    first_aid: 'Busque atendimento médico imediatamente. Não tente sugar o veneno ou fazer cortes.',
    image: 'https://static.nationalgeographicbrasil.com/files/styles/image_3200/public/cobra-coral.jpg?w=1600&h=1067',
    characteristics: ['Anéis vermelhos, pretos e brancos', 'Corpo cilíndrico e esbelto', 'Cabeça pequena e arredondada', 'Focinho vermelho'],
  },
  {
    id: 4,
    name: 'Coral-falsa',
    scientific: 'Oxyrhopus trigeminus',
    venomous: false,
    venom_type: null,
    protected: false,
    protection_status: 'Não ameaçada',
    description: 'Imita visualmente a coral-verdadeira, sendo frequentemente morta por engano. Não representa perigo para humanos.',
    first_aid: null,
    image: 'https://s2-g1.glbimg.com/KC3zMje-v0rLfl4xEUfCFaSx67Q=/0x0:1625x1080/1008x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2018/X/A/AZ7F6MT8CwyXLjgYZcjw/erythrolamprus-aesculapii-2.jpg',
    characteristics: ['Anéis vermelhos e pretos sem branco', 'Corpo mais robusto que a coral-verdadeira', 'Cabeça levemente distinta do corpo', 'Olhos maiores'],
  },
  {
  id: 5,
  name: 'Cobra-verde',
  scientific: 'Philodryas nattereri',
  venomous: false,
  venom_type: 'Opistóglifa (veneno fraco - risco muito baixo)',
  protected: false,
  protection_status: 'Não ameaçada',
  description: 'A espécie mais comum da Caatinga. Ágil e arborícola. Possui glândulas de veneno e presas traseiras, mas o veneno é muito fraco e raramente causa envenenamento em humanos. É considerada de baixo risco, mas classificada como peçonhenta por precaução.',
  first_aid: 'Lave o local com água e sabão. Observe sinais de infecção. Em caso de sintomas incomuns, procure atendimento médico.',
  image: 'https://static.inaturalist.org/photos/703400083/large.jpg',
  characteristics: ['Coloração verde', 'Corpo esbelto e alongado', 'Olhos grandes', 'Muito ágil'],
},
  {
    id: 6,
    name: 'Jiboia',
    scientific: 'Boa constrictor',
    venomous: false,
    venom_type: null,
    protected: true,
    protection_status: 'Protegida em vários estados',
    description: 'Mata por constrição, não possui veneno. Muito caçada no interior. Importante para o equilíbrio do ecossistema.',
    first_aid: null,
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/720484757/large.jpg',
    characteristics: ['Corpo grande e robusto', 'Padrão de manchas em selas', 'Cabeça alongada e distinta', 'Pode atingir mais de 3 metros'],
  },
];
